name: Run EditMode and PlayMode Test

on:
  pull_request:
    branches:
      - feature/*
  push:
    branches:
      - feature/*

jobs:
  test:
    name: Run EditMode and PlayMode Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UnityProject.
        uses: actions/checkout@v2

      - name: Run EditMode and PlayMode Test
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2021.2.8f1
          # [All, PlayMode, EditMode]
          testMode: All
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
